on: [push]
name: Deploy
jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - uses: okteto/namespace@master
      - name: "Create stack"
        uses: okteto/deploy-stack@master
        with:
          build: "true"
